gems:
  - jekyll-sitemap


# Site settings
title: Den personlige genvej til et rent samarbejde
email: lofaren@lofaren.dk
description: 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lofaren.dk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
